# TestPelaDeploy.py

# ================================================================================
# BOOST SOFTWARE LICENSE
#
# Copyright 2020 BitWise Laboratories Inc.
# Original Author.......Jim Waschura
# Contact...............info@bitwiselabs.com
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# ================================================================================

from pyBitwiseAutomation import *
import sys
import math


def test_PelaDeploy(
        ip_address: str,
        loop_count: int = 1,
        verbose_flag: bool = False,
        prbs_flag: bool = False,
        channel: BranchPatt.PatternChannel = BranchPatt.PatternChannel.Ch0
) -> int:
    # returns number of errors encountered

    print("ip_addr=" + ip_address + ", loop=" + str(loop_count) +
          ", ch=" + str(channel) +", prbs="+str(prbs_flag))

    errors = 0
    Pela = PelaDevice()
    channel_num = 0 if channel == BranchPatt.PatternChannel.Ch0 else 1
    counter = 0

    try:
        ## Pela.setDebugging(verbose_flag)
        Pela.Connect(ip_address)

        if verbose_flag:
            print("Pela DEPLOY TEST")
            print("IP Address........" + ip_address)
            print("Serial number....." + Pela.Const.getSN())
            print("Build............." + Pela.Sys.getBuild())
            # print("Architecture......" + Pela.Sys.getArchitecture())
            print("Loop.............." + str(loop_count))
            print("Verbose..........." + str(verbose_flag))
            print("Channel..........." + str(channel))

        # Pela.RestoreConfiguration("[factory]")

        ed_clk = Pela.ED.getDataRateGHz()
        print("ED Data Rate: " + str(ed_clk) + " Gbps")

        temp_c = Pela.getTemperatureC()
        print("Temperature: {:.2f}".format(temp_c))

        fnames = []
        if prbs_flag:
            ## bad on Pela:
            ## fnames.append("Prbs/prbs13.patt")
            ## fnames.append("Prbs/invPrbs13.patt")
            ## good:
            ## fnames.append("Prbs/prbs07.patt")
            ## fnames.append("Prbs/invPrbs07.patt")
            ## good:
            ## fnames.append("Prbs/prbs09.patt")
            ## fnames.append("Prbs/invPrbs09.patt")
            fnames.append("Prbs/prbs11.patt")
            fnames.append("Prbs/invPrbs11.patt")
        else:
            fnames.append("1100.patt")
            fnames.append("10.patt")

        while counter < loop_count:
            time_start = time.time()
            error_msg = "Okay"
            try:
                time.sleep(0.5)
                Pela.Patt.Deploy(channel, fnames[counter % len(fnames)], 0)

            except Exception as e:
                errors += 1
                error_msg = "Error"

            counter += 1
            time_elapsed = time.time() - time_start

            print(str(channel) +
                  ", " + str(ed_clk) + " Gbps" +
                  ", loop=" + str(counter) +
                  ", " + error_msg +
                  ", " + "{:.2f}".format(time_elapsed) + " sec" +
                  ", file=" + fnames[counter % len(fnames)]
                  )

    finally:
        Pela.Disconnect()
        Pela = None

    return errors


if __name__ == '__main__':
    print("TestPelaDeploy, Version 1.1\n")

    loop = 1
    ip = ""
    verbose = False
    channel = []
    prbs = False

    i = 1
    while i < len(sys.argv):
        ## print("argv[" + str(i) + "] = " + sys.argv[i])

        if sys.argv[i] == "-loop":
            loop = int(sys.argv[i + 1])
            i += 1
        elif sys.argv[i] == "-verbose":
            verbose = True
        elif sys.argv[i] == "-prbs":
            prbs = True
        elif sys.argv[i] == "-ch":
            if int(sys.argv[i + 1]) == 0:
                channel.append(BranchPatt.PatternChannel.Ch0)
            elif int(sys.argv[i + 1]) == 1:
                channel.append(BranchPatt.PatternChannel.Ch1)
            else:
                print("Unknown channel number. Must be 0 or 1")
            i += 1
        elif ip == "":
            ip = sys.argv[i]
        else:
            print("Unknown command-line argument: " + sys.argv[i])

        i += 1

    if ip == "" or loop < 1:
        print("Usage:  TestPelaDeploy [options] <ip-address>")
        print("Options:  -loop N .... set looping count (dflt 1)")
        print("          -prbs ...... use longer prbs files")
        print("          -ch N ...... set channel 0 or 1 to test (multiple allowed)")
        print("          -verbose ... set verbose mode for debugging")
        exit()

    if len(channel) == 0:
        channel.append(BranchPatt.PatternChannel.Ch0)

    summary = []
    total_errors = 0

    try:
        for ch in channel:
            errors_encountered = test_PelaDeploy(ip, loop, verbose, prbs, ch)
            total_errors = total_errors + errors_encountered
            summary.append(errors_encountered)

    except KeyboardInterrupt:
        print("\nCtrl-C encountered")

    print("Error summary:")

    for n in range(len(summary)):
        print(str(channel[int(n)]) +
              ", Errors=" + str(summary[n]))

    print("Total errors: " + str(total_errors))

# EOF
