//================================================================================
// BOOST SOFTWARE LICENSE
//
// Copyright 2020 BitWise Laboratories Inc.
// Author.......Jim Waschura
// Contact......info@bitwiselabs.com
//
//Permission is hereby granted, free of charge, to any person or organization
//obtaining a copy of the software and accompanying documentation covered by
//this license (the "Software") to use, reproduce, display, distribute,
//execute, and transmit the Software, and to prepare derivative works of the
//Software, and to permit third-parties to whom the Software is furnished to
//do so, all subject to the following:
//
//The copyright notices in the Software and this entire statement, including
//the above license grant, this restriction and the following disclaimer,
//must be included in all copies of the Software, in whole or in part, and
//all derivative works of the Software, unless such copies or derivative
//works are solely in the form of machine-executable object code generated by
//a source language processor.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//DEALINGS IN THE SOFTWARE.
//================================================================================

#include <stdio.h>
#include <unistd.h> /* usleep */
#include <stdlib.h> /* free */
#include <math.h> /* log10 */

#include "StepscopeDevice.h"

void test_stepscope(char *ip_address, bool stopOnError, int run);

int main( int argc, char *argv[] )
{
	setbuf(stdout, NULL); /* disable stdout buffering */
	printf("TestStepscope, Version 1.0\n");

	bool stopOnError=false;
	char *ip[32];
	int ipCount=0;
	int repeat=1;

	while( *(++argv) )
		if( !strcmp( *argv, "-stop") )
			stopOnError=true;

		else if( !strcmp( *argv, "-repeat") )
			repeat=atoi(*(++argv));
		else if( ipCount<32 )
			ip[ipCount++] = *argv;
		else
		{
			printf("Too many IP addresses, maximum is 32\n");
			exit(0);
		}

	if( ipCount==0 || repeat<1 )
	{
		printf("Usage:  TestStepscope [options] IP0 IP1 ... IPn\n");
		printf("Options:  -stop ..... stop on first error\n");
		printf("          -repeat N.. number of tests for each IP\n");
		exit(0);
	}

	try
	{
		for( int n=0; n<ipCount; n++ )
			for( int k=0; k<repeat; k++ )
				test_stepscope(ip[n],stopOnError,k+1);
	}
	catch(const char*msg)
	{
		printf("\nError: %s\n", msg );
	}

	return 0;
}

void test_stepscope(char *ip_address, bool stopOnError, int run )
{
	if( ip_address==0 || ip_address[0]==0 )
		throw "[Invalid_Parameter]";

	StepscopeDevice Stepscope;

	Stepscope.Connect( ip_address );

	char serialNumber[1024];
	Stepscope.Const.getSN( serialNumber, 1024 );

	char buffer[4096];
	printf("STEPSCOPE TEST\n");
	printf("IP Address........%s\n", ip_address );
	printf("Serial number.....%s\n", serialNumber ) ;
	printf("Build.............%s\n", Stepscope.Sys.getBuild( buffer, 4096 )) ;
	printf("StopOnError.......%c\n", stopOnError?'T':'F');

	//================================================================================
	//================================================================================

	Stepscope.Stop();
	Stepscope.RestoreConfiguration("[factory]");

	Stepscope.Pulse.setAmplMV(300.0);
	Stepscope.Pulse.setMode(BranchPulse::Mode::Local);
	Stepscope.Pulse.setLength(8);

    Stepscope.Tdr.Window.setEnabled(false);    // 03-15-2024 (begin)
    Stepscope.Tdr.Window.setRangePS(0.0, 1e6);
    double value_from = Stepscope.Tdr.Window.getRangePS(0);
    double value_to = Stepscope.Tdr.Window.getRangePS(1);
    printf("TDR Window range is set to: %lf - %lf\n", value_from, value_to );
    Stepscope.Tdr.Window.Clear();   // 03-15-2024 (end)



	Stepscope.App.setTab("STEP");

	Stepscope.Step.Cfg.setReclen(1024);
	Stepscope.Step.Align( BranchStep::AlignMode::align0101 );

	Stepscope.WaitForRunToComplete(90);
	Stepscope.App.Stop();
	Stepscope.Step.Fit();

	int byteCount=0;
	float *data = (float*) Stepscope.Step.getBinary(&byteCount);
	if( data!=0 && byteCount>0 )
	{
		float minimum = data[0];
		float maximum = data[0];
		for( int n=1; n<byteCount/(int)sizeof(float); n++ )
		{
			if( data[n]<minimum )
				minimum = data[n];
			if( data[n]>maximum )
				maximum = data[n];
		}
		printf("Minimum.....%.2lf\n", minimum );
		printf("Maximum.....%.2lf\n", maximum );
		printf("Amplitude...%.2lf\n", maximum-minimum );
	}

	Stepscope.Disconnect();
}

